spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight: true

    defer-datasource-initialization: true

jwt:
  secret-key: ${JWT_SECRET:this-is-secret-key-replace-with-your-own-secret-key}
  expiration: 1800000
  refresh-token:
    expiration: 86400000000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha


