spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight: true

    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

jwt:
  issuer: ${ISSUER:untouchable.com}
  secret_key: ${JWT_SECRET:dGhpcy1pcy1zZWNyZXQta2V5LXJlcGxhY2Utd2l0aC15b3VyLW93bi1zZWNyZXQta2V5} # this-is-secret-key-replace-with-your-own-secret-key
  access_token_expiration: 1800 # 30 minutes
  refresh_token_expiration: 86400000 # 1 day

stroage:
  imgbb:
    api-key: ${IMGBB_API_KEY:your-imgbb-api-key}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha


