spring:
  config:
    activate:
      on-profile: test

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret: agelknselgnkgselkngeslnk


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
        descriptor.sql: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html

